# Generated by Django 4.2.1 on 2023-05-29 18:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user/default.jpeg', null=True, upload_to=core.models.user_image_file_path),
        ),
    ]
